stages:
    - deploy

deploy_preview:
    stage: deploy
    except:
        - main
    script:
        - pnpm run deploy --token=$VERCEL_TOKEN

deploy_production:
    stage: deploy
    only:
        - main
    script:
        - pnpm run deploy:prod --token=$VERCEL_TOKEN
