stages:
    - deploy

deploy_preview:
    stage: deploy
    except:
        - main
    script:
        - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN --name=soulful
        - vercel deploy --token=$VERCEL_TOKEN --name=soulful

deploy_production:
    stage: deploy
    only:
        - main
    script:
        - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        - vercel deploy --prod --token=$VERCEL_TOKEN
