stages:
    - deploy

deploy_preview:
    stage: deploy
    except:
        - main
    script:
        - vercel pull --yes --token=$VERCEL_TOKEN --environment=preview
        - vercel build --yes --token=$VERCEL_TOKEN
        - vercel deploy --yes --prebuilt --token=$VERCEL_TOKEN

deploy_production:
    stage: deploy
    only:
        - main
    script:
        - vercel pull --yes --token=$VERCEL_TOKEN --environment=production
        - vercel build --yes --prod --token=$VERCEL_TOKEN
        - vercel deploy --yes --prebuilt --prod --token=$VERCEL_TOKEN
