stages:
    - deploy

deploy_preview:
    stage: deploy
    except:
        - main
    script:
        - vercel build --yes --token=$VERCEL_TOKEN
        - vercel deploy --prebuilt --yes --token=$VERCEL_TOKEN

deploy_production:
    stage: deploy
    only:
        - main
    script:
        - vercel build --prod --yes --token=$VERCEL_TOKEN
        - vercel deploy --prebuilt --prod --yes --token=$VERCEL_TOKEN
