stages:
    - deploy

deploy_preview:
    stage: deploy
    except:
        - main
    script:
        - vercel deploy --yes --token=$VERCEL_TOKEN

deploy_production:
    stage: deploy
    only:
        - main
    script:
        - vercel deploy --yes --prod --token=$VERCEL_TOKEN
