export const MAX_TITLE_LENGTH = 50;
export const MAX_LANDING_POSTS_DESCRIPTION_LENGTH = 100;
export const MAX_POSTS_DESCRIPTION_LENGTH = 300;

export const DEFAULT_LIMIT = 9;

export const DAY_MS = 86400000;
